import type { Metadata } from "next";
import { Geist_Mono, Inter, Noto_Serif } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import LenisProvider from "@/provider/LenisProvider";
import ModelLoadingProvider from "@/components/ModelLoadingProvider";
import ModelLoadingOverlay from "@/components/ModelLoadingOverlay";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const notoSerif = Noto_Serif({
  variable: "--font-noto-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kato Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistMono.variable} ${notoSerif.variable} antialiased`}
      >
        <LenisProvider>
          <ModelLoadingProvider>
            <ModelLoadingOverlay />
            <Navbar />
            {children}
          </ModelLoadingProvider>
        </LenisProvider>
      </body>
    </html>
  );
}
