/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Adamante (https://sketchfab.com/Adamant6686)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sphere-and-rotated-rings-51792914ce6c442ca36153c4c06e55e5
Title: Sphere and rotated rings
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { Group, Mesh } from "three";

export default function Model(props: {
  position: [number, number, number];
  scale: number;
}) {
  const group = useRef<Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "model/sphere_and_rotated_rings.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions.CINEMA_4D_Main) {
      actions.CINEMA_4D_Main.setDuration(15);
      actions.CINEMA_4D_Main.play();
    }
  }, [actions.CINEMA_4D_Main]);

  return (
    <>
      <group ref={group} {...props} dispose={null}>
        <group name="Sketchfab_Scene">
          <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
            <group
              name="f85ff437812d471ca26a36bfdfd21a0efbx"
              rotation={[Math.PI / 2, 0, 0]}
            >
              <group name="Object_2">
                <group name="RootNode">
                  <group
                    name="CINEMA_4D_Editor"
                    position={[658.618, 597.36, 558.515]}
                    rotation={[-Math.PI, 0.668, 2.551]}
                  >
                    <group name="Object_5" />
                  </group>
                  <group name="Sphere">
                    <mesh
                      name="Sphere_Mat1_0"
                      castShadow
                      receiveShadow
                      geometry={(nodes.Sphere_Mat1_0 as Mesh).geometry}
                      material={materials["Mat.1"]}
                    />
                  </group>
                  <group name="Tube">
                    <mesh
                      name="Tube_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={(nodes.Tube_Mat_0 as Mesh).geometry}
                    >
                      <meshStandardMaterial
                        color="#ffeca1"
                        metalness={1}
                        roughness={0.08}
                      />
                    </mesh>
                  </group>

                  <group name="Tube_2" rotation={[0, 0, Math.PI / 2]}>
                    <mesh
                      name="Tube_2_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={(nodes.Tube_2_Mat_0 as Mesh).geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Tube_1" visible={false} />
                  <group visible={false} name="Tube_3" />
                  <group visible={false} name="Tube_4" />
                  <group visible={false} name="Tube_6" />
                  <group visible={false} name="Tube_5" />
                  <group visible={false} name="Tube_7" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </>
  );
}

useGLTF.preload("model/sphere_and_rotated_rings.glb");
